urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import (
    EntityCreateView,
    EntityDetailView,
    EntityListView,
    EntityUnstagedListView,
    EntityUpdateView,
    MaterialImageListView,
    SceneCreateView,
    SceneDetailView,
    SceneListView,
    SceneUpdateView,
    StagingDetailView,
    StagingListView,
    StagingUpdateView,
    entity_delete,
    entity_unstaged_delete,
    material_image_create,
    material_image_delete,
    scene_delete,
    staged_entity_create,
    staging_delete,
)

app_name = "djaframe"
urlpatterns = [
    path("", RedirectView.as_view(pattern_name="djaframe:scene_list")),
    path("entity/", EntityListView.as_view(), name="entity_list"),
    path("entity/add/", EntityCreateView.as_view(), name="entity_create"),
    path("entity/unstaged/", EntityUnstagedListView.as_view(), name="entity_unstaged"),
    path(
        "entity/unstaged/delete/", entity_unstaged_delete, name="entity_unstaged_delete"
    ),
    path("entity/<pk>/", EntityDetailView.as_view(), name="entity_detail"),
    path("entity/<pk>/update/", EntityUpdateView.as_view(), name="entity_update"),
    path("entity/<pk>/delete/", entity_delete, name="entity_delete"),
    path("entity/<pk>/matimg/", MaterialImageListView.as_view(), name="matimg_list"),
    path("entity/<pk>/matimg/add/", material_image_create, name="matimg_create"),
    path("matimg/<pk>/", material_image_delete, name="matimg_delete"),
    path("scene/", SceneListView.as_view(), name="scene_list"),
    path("scene/add/", SceneCreateView.as_view(), name="scene_create"),
    path("scene/<pk>/", SceneDetailView.as_view(), name="scene_detail"),
    path("scene/<pk>/update/", SceneUpdateView.as_view(), name="scene_update"),
    path("scene/<pk>/delete/", scene_delete, name="scene_delete"),
    path("scene/<pk>/staging/", StagingListView.as_view(), name="staging_list"),
    path("scene/<pk>/staging/add/", staged_entity_create, name="staging_create"),
    path("staging/<pk>/", StagingDetailView.as_view(), name="staging_detail"),
    path("staging/<pk>/update/", StagingUpdateView.as_view(), name="staging_update"),
    path("staging/<pk>/delete/", staging_delete, name="staging_delete"),
]

models.py
from math import asin, atan2, copysign, cos, degrees, fabs, pi
from pathlib import Path

import ezdxf
import numpy as np
from django.conf import settings
from django.core.files import File
from django.core.validators import FileExtensionValidator
from django.db import models
from ezdxf import colors
from ezdxf.addons import meshex
from ezdxf.math import Vec3
from ezdxf.render import MeshBuilder


def entity_directory_path(instance, filename):
    return "uploads/djaframe/obj/{0}/{1}".format(instance.id, filename)


class Entity(models.Model):

    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500, null=True, blank=True)
    gltf_model = models.FileField(
        "GLTF file",
        help_text="Overrides all other entries",
        max_length=200,
        upload_to="uploads/djaframe/entity/",
        validators=[
            FileExtensionValidator(
                allowed_extensions=[
                    "gltf",
                    "glb",
                ]
            )
        ],
        null=True,
        blank=True,
    )
    obj_model = models.FileField(
        "OBJ file",
        max_length=200,
        upload_to="uploads/djaframe/entity/",
        validators=[
            FileExtensionValidator(
                allowed_extensions=[
                    "obj",
                ]
            )
        ],
        null=True,
        blank=True,
    )
    mtl_model = models.FileField(
        "MTL file",
        max_length=200,
        upload_to="uploads/djaframe/entity/",
        validators=[
            FileExtensionValidator(
                allowed_extensions=[
                    "mtl",
                ]
            )
        ],
        null=True,
        blank=True,
    )
    switch = models.BooleanField(default=False, help_text="Switch Z/Y axis")

    class Meta:
        verbose_name = "Entity"
        verbose_name_plural = "Entities"

    def __str__(self):
        return self.title

    def check_material_file_name(self):
        # this function should be called only if
        # obj_model and mtl_model exist

        # get the material file name
        mtl_name = self.mtl_model.name.split("/")[-1]
        # get file paths for object file and helper file
        helper_path = Path(settings.MEDIA_ROOT).joinpath(
            "uploads/djaframe/scene/temp.obj"
        )
        obj_path = Path(self.obj_model.path)
        # copy helper from object file
        with open(obj_path, "r") as o_f, open(helper_path, "w") as h_f:
            for line in o_f:
                if line.startswith("mtllib"):
                    h_f.write(f"mtllib {mtl_name}\n")
                else:
                    h_f.write(line)
        # copy object file back
        with open(obj_path, "w") as o_f, open(helper_path, "r") as h_f:
            for line in h_f:
                o_f.write(line)

    def check_image_file_name(self):
        # this function should be called only if
        # images and mtl_model exist

        # get image names as a dictionary
        image_dict = {}
        for img in self.material_images.all():
            img_name = img.image.name.split("/")[-1]
            image_dict[img_name.split(".")[0]] = img_name.split(".")[1]
        # get file paths for material file and helper file
        helper_path = Path(settings.MEDIA_ROOT).joinpath(
            "uploads/djaframe/scene/temp.obj"
        )
        mtl_path = Path(self.mtl_model.path)
        # copy helper from material file
        with open(mtl_path, "r") as m_f, open(helper_path, "w") as h_f:
            for line in m_f:
                if "map_Ka " in line:
                    start = line.split("map_Ka ")[0]
                    rest = line.split("map_Ka ")[-1]
                    name = rest.split(".")[0]
                    for key, value in image_dict.items():
                        if name == key:
                            h_f.write(line)
                        elif name in key:
                            h_f.write(f"{start}map_Ka {key}.{value}\n")
                elif "map_Kd " in line:
                    start = line.split("map_Kd ")[0]
                    rest = line.split("map_Kd ")[-1]
                    name = rest.split(".")[0]
                    for key, value in image_dict.items():
                        if name == key:
                            h_f.write(line)
                        elif name in key:
                            h_f.write(f"{start}map_Kd {key}.{value}\n")
                else:
                    h_f.write(line)
        # copy material file back
        with open(mtl_path, "w") as m_f, open(helper_path, "r") as h_f:
            for line in h_f:
                m_f.write(line)


def material_image_directory_path(instance, filename):
    return "uploads/djaframe/obj/{0}/{1}".format(instance.entity.id, filename)


class MaterialImage(models.Model):
    entity = models.ForeignKey(
        Entity,
        on_delete=models.CASCADE,
        related_name="material_images",
        verbose_name="Material image",
    )
    image = models.ImageField(upload_to="uploads/djaframe/entity/")

    def __str__(self):
        return Path(self.image.url).name


class Scene(models.Model):

    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500, null=True, blank=True)
    image = models.ImageField(
        upload_to="uploads/djaframe/scene/",
        null=True,
        blank=True,
        help_text="Equirectangular image",
    )
    dxf = models.FileField(
        "DXF file",
        help_text="Please, transform 3DSolids into Meshes before upload",
        max_length=200,
        upload_to="uploads/djaframe/scene/",
        null=True,
        blank=True,
        validators=[
            FileExtensionValidator(
                allowed_extensions=[
                    "dxf",
                ]
            )
        ],
    )

    class Meta:
        verbose_name = "Scene"
        verbose_name_plural = "Scenes"

    def __str__(self):
        return self.title

    __original_dxf = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_dxf = self.dxf

    def save(self, *args, **kwargs):
        # save and eventually upload DXF
        super().save(*args, **kwargs)
        if self.__original_dxf != self.dxf:
            all_objects = self.staged_entities.all()
            if all_objects.exists():
                all_objects.delete()
            self.create_objs_from_dxf()

    def create_objs_from_dxf(self):
        doc = ezdxf.readfile(self.dxf.path)
        # make layer dict
        layer_dict = {}
        for layer in doc.layers:
            if layer.rgb:
                color = cad2hex(layer.rgb)
            else:
                color = cad2hex(layer.color)
            layer_dict[layer.dxf.name] = color
        # get model space
        msp = doc.modelspace()
        # prepare two helper files
        path = Path(settings.MEDIA_ROOT).joinpath("uploads/djaframe/scene/temp.obj")
        path2 = Path(settings.MEDIA_ROOT).joinpath("uploads/djaframe/scene/temp2.obj")
        # iterate over layers
        for name, color in layer_dict.items():
            # write first file recording vertex number
            with open(path, "w") as f:
                for m in msp.query(f"MESH[layer=='{name}']"):
                    mb = MeshBuilder()
                    mb.vertices = Vec3.list(m.vertices)
                    mb.faces = m.faces
                    f.write(meshex.obj_dumps(mb))
                    f.write(f"# total vertices={len(m.vertices)}\n")
            # pass values from one file to the other
            with open(path, "r") as f, open(path2, "w") as f2:
                # file is empty, pass
                if len(f.readlines()) == 0:
                    continue
                # rewind file!
                f.seek(0)
                f2.write("# Generated by django-a-frame\n")
                # offset face number by total vertex number
                n = 0
                for line in f:
                    if line.startswith("v"):
                        f2.write(line)
                    elif line.startswith("# total vertices="):
                        n += int(line.split("=")[1])
                    elif line.startswith("f"):
                        fc = line.split(" ")
                        f2.write(f"f {int(fc[1])+n} {int(fc[2])+n} {int(fc[3])+n}\n")
            with open(path2, "r") as f:
                entity = Entity.objects.create(
                    title=f"Layer {name}",
                    description="Generated by django-a-frame",
                    switch=True,
                    obj_model=File(f, name="object.obj"),
                )
                Staging.objects.create(
                    scene=self,
                    entity=entity,
                    color=color,
                    data={"Layer": name},
                )
        # iterate over blocks
        for block in doc.blocks:
            if block.name in [
                "*Model_Space",
            ]:
                continue
            # write first file recording vertex number
            with open(path, "w") as f:
                for m in block.query("MESH"):
                    mb = MeshBuilder()
                    mb.vertices = Vec3.list(m.vertices)
                    mb.faces = m.faces
                    f.write(meshex.obj_dumps(mb))
                    f.write(f"# total vertices={len(m.vertices)}\n")
            # pass values from one file to the other
            with open(path, "r") as f, open(path2, "w") as f2:
                # file is empty, pass
                if len(f.readlines()) == 0:
                    continue
                # rewind file!
                f.seek(0)
                f2.write("# Generated by django-a-frame\n")
                # offset face number by total vertex number
                n = 0
                for line in f:
                    if line.startswith("v"):

templates/djaframe/htmx/entity_create.html
{% load crispy_forms_tags %}
{% load i18n %}

<div class="card mx-auto" style="max-width: 480px">
  <div class="card-header">
    <h4 class="card-title">{% trans "Create entity"%}</h4>
  </div>
  <div class="card-body">
    <form>
      {{ form|crispy }}
      <button class="btn btn-primary"
              type="submit"
              hx-post="{% url 'djaframe:entity_create' %}"
              hx-target="#content"
              hx-push-url="true">
        {% trans "Add entity" %}
      </button>
    </form>
  </div>
</div>

templates/djaframe/htmx/entity_delete.html
{% load i18n %}

<div class="alert alert-danger"
     hx-get="{% url 'djaframe:entity_list' %}"
     hx-target="#content"
     hx-trigger="load delay:300ms">
  {% trans "Deleting..." %}<span class="spinner-border spinner-border-sm"></span>
</div>

templates/djaframe/htmx/entity_detail.html
{% load i18n %}

<div class="card" id="entity-detail-card">
  <div class="card-header">
    <h4 class="card-title">{% trans "Entity:"%} {{ object.title }}</h4>
  </div>
  <div class="card-body">
    <a-scene style="width: 100%; height: 600px" embedded>
      <a-assets>
        {% if object.gltf_model %}
          <a-asset-item id="gltf-file" src="{{ object.gltf_model.url }}"></a-asset-item>
        {% else %}
          <a-asset-item id="obj-file" src="{{ object.obj_model.url }}"></a-asset-item>
          {% if object.mtl_model %}<a-asset-item id="mtl-file" src="{{ object.mtl_model.url }}"></a-asset-item>{% endif %}
        {% endif %}
      </a-assets>
      {% if object.gltf_model %}
        <a-entity gltf-model="#gltf-file"></a-entity>
      {% else %}
        <a-entity obj-model="obj: #obj-file{% if object.mtl_model %}; mtl: #mtl-file{% endif %}"
                  {% if object.switch %}rotation="-90 0 0"{% endif %}>
        </a-entity>
      {% endif %}
    </a-scene>
  </div>
  <div class="card-footer">
    <div class="row text-center">
      <a class="link link-primary col"
         hx-get="{% url 'djaframe:entity_list' %}"
         hx-target="#content"
         hx-push-url="true">
        {% trans "Back to list"%}
      </a>
      {% if perms.djaframe.change_entity %}
        <a class="link link-primary col"
           hx-get="{% url 'djaframe:entity_update' pk=object.id %}"
           hx-target="#content"
           hx-push-url="true">
          {% trans "Modify" %}
        </a>
      {% endif %}
      {% if perms.djaframe.delete_entity %}
        <a class="link link-danger col"
           hx-get="{% url 'djaframe:entity_delete' pk=object.id %}"
           hx-target="#entity-detail-card"
           hx-swap="outerHTML"
           hx-confirm="{% trans 'Are you sure you want to delete this entity?' %}">
          {% trans "Delete" %}
        </a>
      {% endif %}
    </div>
  </div>
</div>

templates/djaframe/htmx/entity_list.html
{% load i18n %}

<div class="card mx-auto" style="max-width: 960px">
  <div class="card-header">
    <h4 class="card-title">{% trans "Entity list"%}</h4>
  </div>
  <div class="card-body">
    {% if object_list %}
      <table class="table">
        <tbody>
          {% for object in object_list %}
            <tr id="entity-row-{{ object.id }}">
              <td>
                <a class="link link-primary"
                   hx-get="{% url 'djaframe:entity_detail' pk=object.id %}"
                   hx-target="#content"
                   hx-push-url="true">
                  {{ object.title }}
                </a>
              </td>
              <td>
                {{ object.description|truncatewords:10 }}
              </td>
              {% if perms.djaframe.change_entity %}
                <td>
                  <a class="link link-primary"
                     hx-get="{% url 'djaframe:entity_update' pk=object.id %}"
                     hx-target="#content"
                     hx-push-url="true">
                    {% trans "Modify" %}
                  </a>
                </td>
              {% endif %}
              {% if perms.djaframe.delete_entity %}
                <td>
                  <a class="link link-danger"
                     hx-get="{% url 'djaframe:entity_delete' pk=object.id %}"
                     hx-target="#entity-row-{{ object.id }}"
                     hx-confirm="{% trans 'Are you sure you want to delete this entity?' %}">
                    {% trans "Delete" %}
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>{% trans "No entities yet" %}</p>
    {% endif %}
    {% if perms.djaframe.add_entity %}
      <button class="btn btn-success"
              hx-get="{% url 'djaframe:entity_create' %}"
              hx-target="#content"
              hx-push-url="true">
        {% trans "Add entity" %}
      </button>
    {% endif %}
    <a class="link link-primary"
       hx-get="{% url 'djaframe:entity_unstaged' %}"
       hx-target="#content"
       hx-push-url="true">
      {% trans "Unstaged entities" %}
    </a>
    -
    <a class="link link-primary"
       hx-get="{% url 'djaframe:scene_list' %}"
       hx-target="#content"
       hx-push-url="true">
      {% trans "Scene list" %}
    </a>
  </div>
</div>

templates/djaframe/htmx/entity_unstaged_list.html
{% load i18n %}

<div id="entity-unstaged-card" class="card mx-auto" style="max-width: 960px">
  <div class="card-header">
    <h4 class="card-title">{% trans "Unstaged Entity list"%}</h4>
  </div>
  <div class="card-body">
    {% if object_list %}
      <table class="table">
        <tbody>
          {% for object in object_list %}
            <tr id="entity-row-{{ object.id }}">
              <td>
                <a class="link link-primary"
                   hx-get="{% url 'djaframe:entity_detail' pk=object.id %}"
                   hx-target="#content"
                   hx-push-url="true">
                  {{ object.title }}
                </a>
              </td>
              <td>
                {{ object.description|truncatewords:10 }}
              </td>
              {% if perms.djaframe.change_entity %}
                <td>
                  <a class="link link-primary"
                     hx-get="{% url 'djaframe:entity_update' pk=object.id %}"
                     hx-target="#content"
                     hx-push-url="true">
                    {% trans "Modify" %}
                  </a>
                </td>
              {% endif %}
              {% if perms.djaframe.delete_entity %}
                <td>
                  <a class="link link-danger"
                     hx-get="{% url 'djaframe:entity_delete' pk=object.id %}"
                     hx-target="#entity-row-{{ object.id }}"
                     hx-confirm="{% trans 'Are you sure you want to delete this entity?' %}">
                    {% trans "Delete" %}
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>{% trans "No unstaged entities" %}</p>
    {% endif %}
    {% if perms.djaframe.delete_entity %}
      {% if object_list %}
        <button class="btn btn-danger"
                hx-get="{% url 'djaframe:entity_unstaged_delete' %}"
                hx-target="#entity-unstaged-card"
                hx-swap="outerHTML"
                hx-confirm="{% trans 'Are you sure you want to delete all unstaged entities?' %}">
          {% trans "Delete all" %}
        </button>
      {% endif %}
    {% endif %}
    <a class="link link-primary"
       hx-get="{% url 'djaframe:entity_list' %}"
       hx-target="#content"
       hx-push-url="true">
      {% trans "All Entity list" %}
    </a>
  </div>
</div>

templates/djaframe/htmx/material_image_create.html
{% load crispy_forms_tags %}
{% load i18n %}

<button id="matimg-create-button"
        class="btn btn-bg btn-success"
        script="on click hide me then show #matimg-create-form"
        {% if invalid_form %}style="display: none"{% endif %}>
  {% trans "Add material image" %}
</button>
<div id="matimg-create-form"
     {% if not invalid_form %}style="display: none"{% endif %}>
  <form>
    {{ matimg_form|crispy }}
    <button class="btn btn-primary"
            type="submit"
            hx-post="{% url 'djaframe:matimg_create' pk=object.id %}"
            hx-target="#matimg-create"
            hx-encoding="multipart/form-data">
      {% trans "Add material image" %}
    </button>
    <button class="btn-close"
            title="{% trans 'Dismiss' %}"
            script="on click hide #matimg-create-form then show #matimg-create-button">
    </button>
  </form>
</div>

templates/djaframe/htmx/material_image_delete.html
{% load i18n %}

<div class="alert alert-danger"
     hx-get="{% url 'djaframe:matimg_list' pk=object.id %}"
     hx-target="#material-images"
     hx-trigger="load delay:300ms">
  {% trans "Deleting..." %}<span class="spinner-border spinner-border-sm"></span>
</div>

templates/djaframe/htmx/scene_create.html
{% load crispy_forms_tags %}
{% load i18n %}

<div class="card mx-auto" style="max-width: 480px">
  <div class="card-header">
    <h4 class="card-title">{% trans "Create scene"%}</h4>
  </div>
  <div class="card-body">
    <form>
      {{ form|crispy }}
      <button class="btn btn-primary"
              type="submit"
              hx-post="{% url 'djaframe:scene_create' %}"
              hx-target="#content"
              hx-push-url="true"
              hx-encoding="multipart/form-data">
        {% trans "Add scene" %}
      </button>
      <button class="btn-close"
              title="{% trans 'Dismiss' %}"
              hx-get="{% url 'djaframe:scene_list' %}"
              hx-target="#content"
              hx-push-url="true">
      </button>
    </form>
  </div>
</div>

templates/djaframe/htmx/scene_delete.html
{% load i18n %}

<div class="alert alert-danger"
     hx-get="{% url 'djaframe:scene_list' %}"
     hx-target="#content"
     hx-trigger="load delay:300ms">
  {% trans "Deleting..." %}<span class="spinner-border spinner-border-sm"></span>
</div>

templates/djaframe/htmx/scene_detail.html
{% load i18n %}

<div class="card" id="scene-detail-card">
  <div class="card-header">
    <h4 class="card-title">{% trans "Scene:"%} {{ object.title }}</h4>
  </div>
  <div class="card-body">
    <a-scene style="width: 100%; height: 600px" embedded>
      {% with stagings=object.staged_entities.all %}
        <a-camera>
          <a-cursor></a-cursor>
          {% for staging in stagings %}
            {% if staging.popupContent %}
              <a-entity id="text-staging-{{ staging.id }}"
                        geometry="primitive: plane; height: 0; width: 0"
                        material="color: white"
                        text="width: 0.5; value: {{ staging.popupContent }}; color: black; wrapCount: 40"
                        visible="false"
                        position="0.3 0 -0.5">
              </a-entity>
            {% endif %}
          {% endfor %}
        </a-camera>
        <a-assets>
          {% if object.image %}<img id="sky-image" src="{{ object.image.url }}">{% endif %}
          {% for staging in stagings %}
            {% if staging.entity.gltf_model %}
              <a-asset-item id="gltf-file-{{ staging.entity.id }}" src="{{ staging.entity.gltf_model.url }}"></a-asset-item>
            {% else %}
              <a-asset-item id="obj-file-{{ staging.entity.id }}" src="{{ staging.entity.obj_model.url }}"></a-asset-item>
              {% if staging.entity.mtl_model %}<a-asset-item id="mtl-file-{{ staging.entity.id }}" src="{{ staging.entity.mtl_model.url }}"></a-asset-item>{% endif %}
            {% endif %}
          {% endfor %}
        </a-assets>
        {% if object.image %}<a-sky src="#sky-image"></a-sky>{% endif %}
        {% for staging in stagings %}
          <a-entity position="{{ staging.position }}"
                    rotation="{{ staging.rotation }}"
                    scale="{{ staging.scale }}">
            {% if staging.entity.gltf_model %}
              <a-entity gltf-model="#gltf-file-{{ staging.entity.id }}"></a-entity>
            {% else %}
              <a-entity obj-model="obj: #obj-file-{{ staging.entity.id }}{% if staging.entity.mtl_model %}; mtl: #mtl-file-{{ staging.entity.id }}{% endif %}"
                        {% if staging.entity.switch %}rotation="-90 0 0"{% endif %}
                        {% if not staging.entity.mtl_model %}material="color: {{ staging.color }}"{% endif %}
                        {% if staging.data %}
                          event-set__enter="_event: mouseenter; _target: #text-staging-{{ staging.id }}; visible: true"
                          event-set__leave="_event: mouseleave; _target: #text-staging-{{ staging.id }}; visible: false"
                        {% endif %}>
              </a-entity>
            {% endif %}
          </a-entity>
        {% endfor %}
      {% endwith %}
    </a-scene>
  </div>
  <div class="card-footer">
    <div class="row text-center">
      <a class="link link-primary col"
         hx-get="{% url 'djaframe:scene_list' %}"
         hx-target="#content"
         hx-push-url="true">
        {% trans "Back to list"%}
      </a>
      {% if perms.djaframe.change_scene %}
        <a class="link link-primary col"
           hx-get="{% url 'djaframe:scene_update' pk=object.id %}"
           hx-target="#content"
           hx-push-url="true">
          {% trans "Modify" %}
        </a>
      {% endif %}
      {% if perms.djaframe.delete_scene %}
        <a class="link link-danger col"
           hx-get="{% url 'djaframe:scene_delete' pk=object.id %}"
           hx-target="#scene-detail-card"
           hx-swap="outerHTML"
           hx-confirm="{% trans 'Are you sure you want to delete this scene?' %}">
          {% trans "Delete" %}
        </a>
      {% endif %}
    </div>
  </div>
</div>

templates/djaframe/htmx/scene_list.html
{% load i18n %}

<div class="card mx-auto" style="max-width: 960px">
  <div class="card-header">
    <h4 class="card-title">{% trans "Scene list"%}</h4>
  </div>
  <div class="card-body">
    {% if object_list %}
      <table class="table">
        <tbody>
          {% for object in object_list %}
            <tr id="scene-row-{{ object.id }}">
              <td>
                <a class="link link-primary"
                   hx-get="{% url 'djaframe:scene_detail' pk=object.id %}"
                   hx-target="#content"
                   hx-push-url="true">
                  {{ object.title }}
                </a>
              </td>
              <td>
                {{ object.description|truncatewords:10 }}
              </td>
              {% if perms.djaframe.change_scene %}
                <td>
                  <a class="link link-primary"
                     hx-get="{% url 'djaframe:scene_update' pk=object.id %}"
                     hx-target="#content"
                     hx-push-url="true">
                    {% trans "Modify" %}
                  </a>
                </td>
              {% endif %}
              {% if perms.djaframe.delete_scene %}
                <td>
                  <a class="link link-danger"
                     hx-get="{% url 'djaframe:scene_delete' pk=object.id %}"
                     hx-target="#scene-row-{{ object.id }}"
                     hx-confirm="{% trans 'Are you sure you want to delete this scene?' %}">
                    {% trans "Delete" %}
                  </a>
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>{% trans "No scenes yet" %}</p>
    {% endif %}
    {% if perms.djaframe.add_scene %}
      <button class="btn btn-success"
              hx-get="{% url 'djaframe:scene_create' %}"
              hx-target="#content"
              hx-push-url="true">
        {% trans "Add scene" %}
      </button>
    {% endif %}
    <a class="link link-primary"
       hx-get="{% url 'djaframe:entity_list' %}"
       hx-target="#content"
       hx-push-url="true">
      {% trans "Entity list" %}
    </a>
  </div>
</div>

templates/djaframe/htmx/scene_update.html
{% load crispy_forms_tags %}
{% load i18n %}

<div class="row mx-auto" style="max-width: 960px">
  <div class="col">
    <div class="card mb-3 mx-auto" style="max-width: 480px">
      <div class="card-header">
        <h4 class="card-title">{% trans "Update scene"%}: {{ object.title }}</h4>
      </div>
      <div class="card-body">
        <form>
          {{ form|crispy }}
          <button class="btn btn-primary"
                  type="submit"
                  hx-post="{% url 'djaframe:scene_update' pk=object.id %}"
                  hx-target="#content"
                  hx-push-url="true"
                  hx-encoding="multipart/form-data">
            {% trans "Update scene" %}
          </button>
          <button class="btn-close"
                  title="{% trans 'Dismiss' %}"
                  hx-get="{% url 'djaframe:scene_detail' pk=object.id %}"
                  hx-target="#content"
                  hx-push-url="true">
          </button>
        </form>
      </div>
    </div>
  </div>
  <div class="col col-xl-6 col-lg-6 col-md-12 col-12">
    <div class="card mx-auto" style="max-width: 480px">
      <div class="card-header">
        {% trans "Staged entities" %}
      </div>
      <div class="card-body">
        <div id="staged-entities"
             hx-get="{% url 'djaframe:staging_list' pk=object.id %}"
             hx-trigger="refreshStagings from:body">
          {% include "djaframe/htmx/staged_entity_loop.html" %}
        </div>
        <div id="staging-create">
          {% include "djaframe/htmx/staging_create.html" %}
        </div>
      </div>
    </div>
  </div>
</div>

templates/djaframe/htmx/staged_entity_loop.html
{% load crispy_forms_tags %}
{% load i18n %}

{% if object.staged_entities.all %}
  {% for staging in object.staged_entities.all %}
    <div class="card mb-2" id="staged-entity-{{ staging.id }}">
      {% include "djaframe/htmx/staging_detail.html" %}
    </div>
  {% endfor %}
{% else %}
  <p>{% trans "No staged entities yet" %}</p>
  <hr>
{% endif %}

templates/djaframe/htmx/staging_delete.html
{% load i18n %}

<div class="alert alert-danger"
     hx-get="{% url 'djaframe:staging_list' pk=object.id %}"
     hx-target="#staged-entities"
     hx-trigger="load delay:300ms">
  {% trans "Deleting..." %}<span class="spinner-border spinner-border-sm"></span>
</div>